export const AUTH_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_STORE_REQUEST: 'LOGIN_STORE_REQUEST',
    LOGIN_STORE_SUCCESS: 'LOGIN_STORE_SUCCESS',
    LOGIN_STORE_FAILURE: 'LOGIN_STORE_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    CLEANUP: 'CLEANUP',
    CHANGE_FIRST_TIME: 'CHANGE_FIRST_TIME'
};